version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.1
  aws-ecr: circleci/aws-ecr@9.0
jobs:
  continuous-integration:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - setup_remote_docker:
          version: 28.5.1
          docker_layer_caching: true

      - aws-ecr/build-and-push-image:
          create-repo: true
          dockerfile: Dockerfile
          path: .
          platform: linux/amd64
          push-image: true
          region: '${AWS_REGION}'
          repo: demo
          registry-id: AWS_ECR_REGISTRY_ID
          repo-scan-on-push: true
          tag: latest

  continuous-delivery:
    machine: true
    resource_class: webiwo/hatespeech
    steps:
      - aws-cli/setup

      - run:
          name: auth to aws ecr
          command: aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 034154586122.dkr.ecr.eu-north-1.amazonaws.com

      - run:
          name: pull image from private repository
          command: docker pull 034154586122.dkr.ecr.eu-north-1.amazonaws.com/hatespeech:latest

      - run:
          name: run image
          command: docker run -d -p 8080:8080 034154586122.dkr.ecr.eu-north-1.amazonaws.com/hatespeech:latest
workflows:
  CICD:
    jobs:
      - continuous-integration
      - continuous-delivery:
          requires:
          - continuous-integration           